python testing_with_lime.py -dataset_name Founta -model_name bert -random_seed 2021
python testing_with_lime.py -dataset_name Founta -model_name bert -random_seed 2022
python testing_with_lime.py -dataset_name Founta -model_name bert -random_seed 2023
python testing_with_lime.py -dataset_name Founta -model_name bert -random_seed 2024
python testing_with_lime.py -dataset_name Founta -model_name bert -random_seed 2025
python testing_with_lime.py -dataset_name Founta -model_name bert_cd -random_seed 2021
python testing_with_lime.py -dataset_name Founta -model_name bert_cd -random_seed 2022
python testing_with_lime.py -dataset_name Founta -model_name bert_cd -random_seed 2023
python testing_with_lime.py -dataset_name Founta -model_name bert_cd -random_seed 2024
python testing_with_lime.py -dataset_name Founta -model_name bert_cd -random_seed 2025
python testing_with_lime.py -dataset_name Basile -model_name bert -random_seed 2021
python testing_with_lime.py -dataset_name Basile -model_name bert -random_seed 2022
python testing_with_lime.py -dataset_name Basile -model_name bert -random_seed 2023
python testing_with_lime.py -dataset_name Basile -model_name bert -random_seed 2024
python testing_with_lime.py -dataset_name Basile -model_name bert -random_seed 2025
python testing_with_lime.py -dataset_name Basile -model_name bert_cd -random_seed 2021
python testing_with_lime.py -dataset_name Basile -model_name bert_cd -random_seed 2022
python testing_with_lime.py -dataset_name Basile -model_name bert_cd -random_seed 2023
python testing_with_lime.py -dataset_name Basile -model_name bert_cd -random_seed 2024
python testing_with_lime.py -dataset_name Basile -model_name bert_cd -random_seed 2025
python testing_with_lime.py -dataset_name Mlma -model_name bert -random_seed 2021
python testing_with_lime.py -dataset_name Mlma -model_name bert -random_seed 2022
python testing_with_lime.py -dataset_name Mlma -model_name bert -random_seed 2023
python testing_with_lime.py -dataset_name Mlma -model_name bert -random_seed 2024
python testing_with_lime.py -dataset_name Mlma -model_name bert -random_seed 2025
python testing_with_lime.py -dataset_name Mlma -model_name bert_cd -random_seed 2021
python testing_with_lime.py -dataset_name Mlma -model_name bert_cd -random_seed 2022
python testing_with_lime.py -dataset_name Mlma -model_name bert_cd -random_seed 2023
python testing_with_lime.py -dataset_name Mlma -model_name bert_cd -random_seed 2024
python testing_with_lime.py -dataset_name Mlma -model_name bert_cd -random_seed 2025
python testing_with_lime.py -dataset_name Davidson -model_name bert -random_seed 2021
python testing_with_lime.py -dataset_name Davidson -model_name bert -random_seed 2022
python testing_with_lime.py -dataset_name Davidson -model_name bert -random_seed 2023
python testing_with_lime.py -dataset_name Davidson -model_name bert -random_seed 2024
python testing_with_lime.py -dataset_name Davidson -model_name bert -random_seed 2025
python testing_with_lime.py -dataset_name Davidson -model_name bert_cd -random_seed 2021
python testing_with_lime.py -dataset_name Davidson -model_name bert_cd -random_seed 2022
python testing_with_lime.py -dataset_name Davidson -model_name bert_cd -random_seed 2023
python testing_with_lime.py -dataset_name Davidson -model_name bert_cd -random_seed 2024
python testing_with_lime.py -dataset_name Davidson -model_name bert_cd -random_seed 2025
python testing_with_lime.py -dataset_name Olid -model_name bert -random_seed 2021
python testing_with_lime.py -dataset_name Olid -model_name bert -random_seed 2022
python testing_with_lime.py -dataset_name Olid -model_name bert -random_seed 2023
python testing_with_lime.py -dataset_name Olid -model_name bert -random_seed 2024
python testing_with_lime.py -dataset_name Olid -model_name bert -random_seed 2025
python testing_with_lime.py -dataset_name Olid -model_name bert_cd -random_seed 2021
python testing_with_lime.py -dataset_name Olid -model_name bert_cd -random_seed 2022
python testing_with_lime.py -dataset_name Olid -model_name bert_cd -random_seed 2023
python testing_with_lime.py -dataset_name Olid -model_name bert_cd -random_seed 2024
python testing_with_lime.py -dataset_name Olid -model_name bert_cd -random_seed 2025
python testing_with_lime.py -dataset_name Waseem -model_name bert -random_seed 2021
python testing_with_lime.py -dataset_name Waseem -model_name bert -random_seed 2022
python testing_with_lime.py -dataset_name Waseem -model_name bert -random_seed 2023
python testing_with_lime.py -dataset_name Waseem -model_name bert -random_seed 2024
python testing_with_lime.py -dataset_name Waseem -model_name bert -random_seed 2025
python testing_with_lime.py -dataset_name Waseem -model_name bert_cd -random_seed 2021
python testing_with_lime.py -dataset_name Waseem -model_name bert_cd -random_seed 2022
python testing_with_lime.py -dataset_name Waseem -model_name bert_cd -random_seed 2023
python testing_with_lime.py -dataset_name Waseem -model_name bert_cd -random_seed 2024
python testing_with_lime.py -dataset_name Waseem -model_name bert_cd -random_seed 2025
