python testing_with_lime_2.py -dataset_name Founta -model_name bert_cd -random_seed 2021 -training_points 50
python testing_with_lime_2.py -dataset_name Founta -model_name bert_cd -random_seed 2022 -training_points 50
python testing_with_lime_2.py -dataset_name Founta -model_name bert_cd -random_seed 2023 -training_points 50
python testing_with_lime_2.py -dataset_name Founta -model_name bert_cd -random_seed 2024 -training_points 50
python testing_with_lime_2.py -dataset_name Founta -model_name bert_cd -random_seed 2025 -training_points 50
python testing_with_lime_2.py -dataset_name Basile -model_name bert_cd -random_seed 2021 -training_points 50
python testing_with_lime_2.py -dataset_name Basile -model_name bert_cd -random_seed 2022 -training_points 50
python testing_with_lime_2.py -dataset_name Basile -model_name bert_cd -random_seed 2023 -training_points 50
python testing_with_lime_2.py -dataset_name Basile -model_name bert_cd -random_seed 2024 -training_points 50
python testing_with_lime_2.py -dataset_name Basile -model_name bert_cd -random_seed 2025 -training_points 50
python testing_with_lime_2.py -dataset_name Mlma -model_name bert_cd -random_seed 2021 -training_points 50
python testing_with_lime_2.py -dataset_name Mlma -model_name bert_cd -random_seed 2022 -training_points 50
python testing_with_lime_2.py -dataset_name Mlma -model_name bert_cd -random_seed 2023 -training_points 50
python testing_with_lime_2.py -dataset_name Mlma -model_name bert_cd -random_seed 2024 -training_points 50
python testing_with_lime_2.py -dataset_name Mlma -model_name bert_cd -random_seed 2025 -training_points 50
python testing_with_lime_2.py -dataset_name Davidson -model_name bert_cd -random_seed 2021 -training_points 50
python testing_with_lime_2.py -dataset_name Davidson -model_name bert_cd -random_seed 2022 -training_points 50
python testing_with_lime_2.py -dataset_name Davidson -model_name bert_cd -random_seed 2023 -training_points 50
python testing_with_lime_2.py -dataset_name Davidson -model_name bert_cd -random_seed 2024 -training_points 50
python testing_with_lime_2.py -dataset_name Davidson -model_name bert_cd -random_seed 2025 -training_points 50
python testing_with_lime_2.py -dataset_name Olid -model_name bert_cd -random_seed 2021 -training_points 50
python testing_with_lime_2.py -dataset_name Olid -model_name bert_cd -random_seed 2022 -training_points 50
python testing_with_lime_2.py -dataset_name Olid -model_name bert_cd -random_seed 2023 -training_points 50
python testing_with_lime_2.py -dataset_name Olid -model_name bert_cd -random_seed 2024 -training_points 50
python testing_with_lime_2.py -dataset_name Olid -model_name bert_cd -random_seed 2025 -training_points 50
python testing_with_lime_2.py -dataset_name Waseem -model_name bert_cd -random_seed 2021 -training_points 50
python testing_with_lime_2.py -dataset_name Waseem -model_name bert_cd -random_seed 2022 -training_points 50
python testing_with_lime_2.py -dataset_name Waseem -model_name bert_cd -random_seed 2023 -training_points 50
python testing_with_lime_2.py -dataset_name Waseem -model_name bert_cd -random_seed 2024 -training_points 50
python testing_with_lime_2.py -dataset_name Waseem -model_name bert_cd -random_seed 2025 -training_points 50
