python testing_with_predictions.py -dataset_name Davidson -model_name Transform_Rationale_SelfAttn_Drpt_corrected -random_seed 2021 -training_points 50
python testing_with_predictions.py -dataset_name Founta -model_name Transform_Rationale_SelfAttn_Drpt_corrected -random_seed 2021 -training_points 50
python testing_with_predictions.py -dataset_name Basile -model_name Transform_Rationale_SelfAttn_Drpt_corrected -random_seed 2021 -training_points 50
python testing_with_predictions.py -dataset_name Olid -model_name Transform_Rationale_SelfAttn_Drpt_corrected -random_seed 2021 -training_points 50
python testing_with_predictions.py -dataset_name Waseem -model_name Transform_Rationale_SelfAttn_Drpt_corrected -random_seed 2021 -training_points 50
